version: "3.5"
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8501:8501"
  db:
   image: postgres:12
   container_name: pgdb
   environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=capstone
         - POSTGRES_DB=postgres
   ports:
         - "6432:5432"
