# .streamlit/secrets.toml
# 

[postgres]
#host = "pgdb"
#port = 5432
#dbname = "postgres"
#user = "postgres"
#password = "capstone"
host = "youtube-recommender-db.cccpvidpnomb.us-east-1.rds.amazonaws.com"
port = 5432
dbname = "initial_youtube_recommender_db"
user = "postgres"
password = "funCapstoneProject510rainbow!!"



